### ISSUE TITLE
Adding option for email token

### ISSUE THREAD

**Issue by jpenns** [reartvapps/homebridge-onstar-dev#3]
@reartvapps Since everybody here in Canada is unable to use an authenticator app until GM gets their act together (which they don't seem interested in) I was told I should ask you if you can add the option of authenticating via an email token. There's already a PHP app to get the token from GM, so all we need is a field where we can use an email based TOTP instead of authenticator based.

Is that possible? On behalf of all Canadians, we'd really appreciate it, especially as winter deepens.

**Comment by reartvapps** [comment]
@jpenns I'll see what I can do. I'm very busy, but I'll be able to look at it at some point.

**Comment by jpenns** [comment]
Thanks! I’m sure we’d all really appreciate it! I got homebridge setup just
in time for the GM plugins to stop working so I’ve been anxiously waiting
for a fix

**Comment by BadLuuck1994** [comment]
what error do you have in your homebridge log ?

**Comment by mgdis4me82** [comment]
> what error do you have in your homebridge log ?

[4/16/2025, 9:00:14 AM] [Acadia] lockDoor: Requested
Authentication failed: SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.get (file:///homebridge/node_modules/homebridge-onstar-dev/node_modules/onstarjs2/dist/index.mjs:31638:31)
    at processResponse (file:///homebridge/node_modules/homebridge-onstar-dev/node_modules/onstarjs2/dist/index.mjs:30563:26)
    at Function.discover (file:///homebridge/node_modules/homebridge-onstar-dev/node_modules/onstarjs2/dist/index.mjs:35114:19)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
[4/16/2025, 9:00:14 AM] [Acadia] lockDoor: Error: Unexpected token '<', "<!doctype "... is not valid JSON

**Comment by BadLuuck1994** [comment]
yep got the same as you. created another issu for this

**Comment by BadLuuck1994** [comment]
did you get a OTA update in you car also?
